Feature/decimal places
hexgis/cmr2_api pull request #16
Opened 2022-06-10 12:44 UTC by smartsena

2022-06-10 12:45 UTC, smartsena commented
![](https://github.trello.services/images/mini-trello-icon.png) [Zeros depois da virgula na tabela para coluna de área](https://trello.com/c/h3kW4fP7/13-zeros-depois-da-virgula-na-tabela-para-coluna-de-%C3%A1rea)

2022-06-10 18:28 UTC, dagnaldo requested changes
Check default value for co_funai

2022-06-10 18:28 UTC, dagnaldo commented on funai/models.py
> +        default=1
Default 1 ?

2022-06-13 21:14 UTC, dagnaldo approved these changes

2022-06-13 21:36 UTC, merged