Creating a data model for Mapoteca
hexgis/cmr2_api pull request #32
Opened 2022-09-08 17:57 UTC by smartsena

2022-09-13 20:22 UTC, dagnaldo requested changes

2022-09-13 20:22 UTC, dagnaldo commented on documental/new_models.py
> +from django.contrib.postgres.fields.jsonb import JSONField
Why is it here?

2022-09-13 20:22 UTC, dagnaldo commented on documental/new_models.py
> +class auth_institution_temp(models.Model):
what is it?

2022-09-14 13:52 UTC, smartsena commented on documental/new_models.py
> +from django.contrib.postgres.fields.jsonb import JSONField
Adjusted.

2022-09-14 15:56 UTC, smartsena commented on documental/new_models.py
> +class auth_institution_temp(models.Model):
Adjusted.

2022-10-26 14:26 UTC, merged